version: '3.8'

services:
  # PostgreSQL para User Service
  user-db:
    image: postgres:16
    container_name: taskforge-user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: taskforge
      POSTGRES_PASSWORD: taskforgepassword
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - taskforge-network

  # PostgreSQL para Project Service
  project-db:
    image: postgres:16
    container_name: taskforge-project-db
    environment:
      POSTGRES_DB: project_db
      POSTGRES_USER: taskforge
      POSTGRES_PASSWORD: taskforgepassword
    ports:
      - "5433:5432"
    volumes:
      - project-db-data:/var/lib/postgresql/data
    networks:
      - taskforge-network

  # PosgreSQL para Notification Service
  notification-db:
    image: postgres:16
    container_name: taskforge-notification-db
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: taskforge
      POSTGRES_PASSWORD: taskforgepassword
    ports:
      - "5434:5432"
    volumes:
      - notification-db-data:/var/lib/postgresql/data
    networks:
      - taskforge-network

  # RabbitMQ para Mensajería Asíncrona
  rabbitmq:
    image: rabbitmq:3-management
    container_name: taskforge-rabbitmq
    ports:
      - "5672:5672"   # Puerto de comunicación
      - "15672:15672" # Dashboard de administración
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - taskforge-network

volumes:
  user-db-data:
  project-db-data:
  notification-db-data:

networks:
  taskforge-network:
    driver: bridge
