name: TaskForge CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven (Including Tests)
      run: mvn -B package --file pom.xml
      
    - name: Docker Compose Validate
      run: docker-compose config
      
  deploy-simulation:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Simulate Deployment Trigger
      run: echo "Despliegue condicional por commits en origin/main. En un entorno real aquí se conectarían workflows de CD (ArgCD, AWS CodeDeploy, etc)."
